### PR TITLE
Add a changelog template

### PR DESCRIPTION
**Pull request by tysongach**
This PR adds a `CHANGELOG.md` template. It’s based on [Keep a Changelog](http://keepachangelog.com/).

I’ve found this format to work quite well on Bourbon; you can see that changelog here: https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md.

### CODE REVIEW

**Comment by mike-burns** [comment]
1. Yes, I like this idea.
2. Historically I have not seen this file named "CHANGELOG", but instead "NEWS". To quote Wikipedia:

> `NEWS` is usually a different file reflecting changes between releases, not between the commits

I tend to think of `CHANGELOG` as `git log > CHANGELOG`, whereas `NEWS` is custom written as part of the release process (commits log vs release notes).

Have you seen such a distinction elsewhere?

**Comment by tysongach** [comment]
@mike-burns Yes, I’ve seen `NEWS` be used. I’m open to either, and I think more thoughtbot projects have a `NEWS.md` file, than do a `CHANGELOG.md`. Personally, I always felt that the term `NEWS` wasn’t as clear of a descriptor; it’s very journalistic.

That said, I’ve put up commit fe6e83dbdd3db640b0994c2010d83457405ef055 which changes the the template file to `NEWS.md` and reframes the intro.

**Comment by mike-burns** [comment]
Yes, love it, +1, etc. etc. :squid: :micronesia: :last_quarter_moon_with_face: :factory:

**Comment by tysongach** [comment]
Thanks, @mike-burns!

**Pull request merged**
