### PR TITLE
Add a pull request template

### PR DESCRIPTION
**Pull request by SViccari**
Summary:
Adds a template for the pull request description.

I noticed @composerinteralia and @seanpdoyle use this template on the dome project and I like :) I've seen other formats like this one from @MattMSumner's [blog posts](https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template):
```
Why:

* ...

This change addresses the need by:

* ...
```
I relate to the submitted format because I typically include a Summary section that's followed by other interesting details. I don't feel strongly about either approach.

### CODE REVIEW

**Comment by SViccari** [comment]
I wonder if this template should include a link to a thoughtbot article about writing a great commit message 🤔 . Writing a helpful pull request description is great but ideally, we want a great commit message that powers a great a pull request description.

**Comment by mike-burns** [comment]
As a person who opens PRs, I'm not a fan of PR templates. I strive to write a commit message that explains what the PR reviewer should know, and I also aim to have one commit at the start of the PR, which means GitHub fills in the description for me.

---

Is the audience of this template our client projects, or our open source? For our client projects the wording in the template makes sense. For an open source project, it is unlikely that the submitter will describe something in a "jobs to be done" style. What do you think?

**Comment by SViccari** [comment]
@mike-burns That's a great point. I was just wondering how a PR description template interacts with a commit message. My guess is the template takes precedence and the commit message isn't populated in the description. Does that sound correct?

If that's true, then that does make a PR template super annoying for those who already write thoughtful commit messages. I don't know how to serve both groups, those who don't need a PR template and those who need guidance...

As for the target audience, I've updated the language with the intent the template could work for a client project or an open source project.

**Comment by mike-burns** [comment]
It concatenates them. It sticks the commit message on top and then the PR template below.

(I actually hit this the other day on my client (they use a PR template): I normally remember to delete the appended template, but the other day I forgot, and had to edit the PR after.)

---

I'm :-1: on this because I don't want it for myself and I wouldn't use it on my open source projects, but I'm happy to have it included in the thoughtbot templates if others find it useful.

**Comment by composerinteralia** [comment]
I also write everything in the commit message, then use that at the PR description, so I don't think this template would be helpful for me personally.

I do like the rubocop pull request template though: https://github.com/rubocop-hq/rubocop/blob/master/.github/PULL_REQUEST_TEMPLATE.md

edit: I like the general idea of a checklist. I am not sure I care that much about "grammatically correct, complete sentences"

**Comment by SViccari** [comment]
Thank you all for the feedback! I'm going to proceed with closing this PR.

**Pull request closed without merging**
