### PR TITLE
Update dynamic README template

### PR DESCRIPTION
**Pull request by stefannibrasil**
I was able to get this workflow running on a test repo: https://github.com/thoughtbot/testing-reusable-repos

We'll need to add the same workflow from the test repo to all of our OSS READMEs.

We can iterate on this as we go but this looks promising. More context can be found on [this Hub message](https://hub.thoughtbot.com/messages/help-with-github-actions-shared-workflow).

### CODE REVIEW

**Comment by stefannibrasil** [comment]
@ayellapragada @nickcharlton @minaslater I spent some time today getting this to work. Here's a test repo using this workflow: https://github.com/thoughtbot/testing-reusable-repos

Do you know if it would be possible to tweak this so that when the `footer` file is updated in this templates repo, the changes propagate to all repos calling this workflow? 🤔  Once the README is rendered with the action, we loose the inline snippet and the README gets updated with the content dynamically. That means, if we change our footer here, we will still need to update all of our repos README so it can get re-rendered. Not that bad as currently it is, but do you see any way around this? I've reached my limit here so hoping to get some ideas from you 😅  Thanks!

**Comment by nickcharlton** [comment]
Hmm, interesting. I notice you're already using some sort of comment to mark the space. A while ago, when I built out my GitHub README I did something similar, but kept them around. It effectively gets re-rendered completely on each run of the Action: https://github.com/nickcharlton/nickcharlton/blob/main/README.md?plain=1

That said, I'm not sure if I'm just repeating what you done already, and I've misunderstood your question! 😅

**Comment by minaslater** [comment]
> @ayellapragada @nickcharlton @minaslater I spent some time today getting this to work. Here's a test repo using this workflow: https://github.com/thoughtbot/testing-reusable-repos
> 
> Do you know if it would be possible to tweak this so that when the `footer` file is updated in this templates repo, the changes propagate to all repos calling this workflow? 🤔 Once the README is rendered with the action, we loose the inline snippet and the README gets updated with the content dynamically. That means, if we change our footer here, we will still need to update all of our repos README so it can get re-rendered. Not that bad as currently it is, but do you see any way around this? I've reached my limit here so hoping to get some ideas from you 😅 Thanks!

Would rerunning the workflow on the test-repo update the README? I _think_ if you update [this line](https://github.com/thoughtbot/testing-reusable-repos/blob/55cdfafb283c4762576462fa863874bd388f663a/.github/workflows/dynamic-readme.yml#L11) to target `main` once this PR is merged, you can use [workflow dispatch](https://github.com/benc-uk/workflow-dispatch) action to kick off the update (rough example below). But idk if that's something you would want living in this repo called templates tho. 

```
name: trigger-testing-repo-readme

on:
  push:
    branches: 
      - main
    paths:
      - templates/footer.md

jobs:
  trigger-workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API repo build/deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-templates
          repo: thoughtbot/testing-reusable-repos
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          ref: 'main'
```

**Comment by stefannibrasil** [comment]
>  I notice you're already using some sort of comment to mark the space

Yes, that's from the Dynamic README GitHub Actions. I'll try keeping the comment there to see if that works. Thanks!

**Comment by stefannibrasil** [comment]
> But idk if that's something you would want living in this repo called templates tho.

That makes sense! I am okay with leaving them here for now and moving them away later. Since they are used for our OSS projects only, it makes sense to me to keep them centralized here. I will try this out, thank you!

**Comment by stefannibrasil** [comment]
Okay, so here's where I am:

- copied @minaslater suggestion to this file: https://github.com/thoughtbot/templates/blob/main/.github/workflows/trigger-dynamic-readme-update.yaml
- created a REPOSITORY_ACCESS_TOKEN secret for this repo (and for the testing repo)
- update the footer file template

Have been getting this Bad Credentials error. Will keep trying but if anyone has any ideas, please let me know! I tried adding `permissions: write` explicitly but still getting the same error.

**Comment by stefannibrasil** [comment]
HA! It worked:

https://github.com/thoughtbot/testing-reusable-repos README has been updated with the changes I made in the template here. THANK YOU, @minaslater 🎉 

I had to create a personal access token, then paste that in the secrets for the repo. Also, had to add [this line](https://github.com/thoughtbot/testing-reusable-repos/blob/main/.github/workflows/dynamic-readme.yml#L7C3-L7C21). Then, it worked.

I'm not sure what is the best way to handle those secrets, though. Is there an organization secret/PAT level that we can use? 🤔

**Pull request merged**
